module Polysemy.Hasql.Table.Query.Update where

-- update ::
--   FoldMapTree 'True () PartialField [PartialSql] tree =>
--   Table d ->
--   Maybe (Where query d) ->
--   query ->
--   PartialTree tree ->
--   Snippet
-- update table qWhere q tree =
--   sql [exon|update #{sel} set |] <>
--   commaSeparatedSnippet (unPartialSql <$> foldMapTree @'True tree) <>
--   foldMap whereSnippet qWhere <>
--   " returning " <>
--   sql (encodeUtf8 cols)
--   where
--     Selector (Sql (encodeUtf8 -> sel)) =
--       table ^. selector
--     whereSnippet (Where _ qw) =
--       " where " <> qw q
--     Sql cols =
--       selectColumns (table ^. structure)
